# Generated by Django 3.0.8 on 2020-07-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='date',
            new_name='year',
        ),
        migrations.AddField(
            model_name='poem',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
