# Generated by Django 3.0.8 on 2020-07-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200717_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clues', to='game.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game.Poem'),
        ),
    ]
